package com.carpool.auth.dto;

import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;

public class UserCreateDTO {

    @NotNull
    @Email
    @ApiModelProperty(notes = "Username used by the user of the app(This should be an email of the user)",required = true)
    private String username;

    @ApiModelProperty(notes = "Full name of the user",required = true)
    private String fullName;

//    private String email;

    @NotNull
    @ApiModelProperty(notes = "Mobile number of the user", required = true)
    private String phoneNumber;

    @NotNull
    @ApiModelProperty(notes = "Password of the user",required = true)
    private String password;

    @NotNull
    @ApiModelProperty(notes = "Password confirmation field, Should match with password",required = true)
    private String password_confirm;

    @ApiModelProperty(notes = "Autogenerated password used to uniquely identifying the user")
    private String userID;

    @ApiModelProperty(notes = "role/roles assigned to this user")
    private String[] roles;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getFullName() {
        return fullName;
    }

    public String[] getRoles() {
        return roles;
    }

    public void setRoles(String[] roles) {
        this.roles = roles;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

//    public String getEmail() {
//        return email;
//    }
//
//    public void setEmail(String email) {
//        this.email = email;
//    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getPassword_confirm() {
        return password_confirm;
    }

    public void setPassword_confirm(String password_confirm) {
        this.password_confirm = password_confirm;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "UserCreateDTO{" +
                "username='" + username + '\'' +
                ", fullName='" + fullName + '\'' +
                //", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
