#version: '3'
#
#services:
#  mysql-auth-server:
#    image: mysql:5.7
#    container_name: oauth-server-sql
#    environment:
#      - MYSQL_ROOT_PASSWORD=sudi
#      - MYSQL_DATABASE=OAuthDB
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=sudi
#    networks:
#      - auth-network
#
#
#  spring-auth-server:
#    image: auth-server
#    container_name: oauth-server-app
#    ports:
#      - 9091:9091
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    networks:
#      - auth-network
#
#networks:
#  auth_auth-network
version: "3"
services:
  mysql-auth-server:
    image: mysql:5.7
    networks:
      - auth-network
    environment:
      - MYSQL_ROOT_PASSWORD=sudi
      - MYSQL_DATABASE=OAuthDB
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sudi

  spring-auth-server:
    image: auth-server
    ports:
      - "9091:9091"
    networks:
      - auth-network
    depends_on:
      - mysql-auth-server
networks:
  auth-network: