server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/OAuthDB?createDatabaseIfNotExist=true
    #url: jdbc:mysql://mysqldb:3306/OAuthDB?createDatabaseIfNotExist=true
    username: root
    password: sudi
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kekovasudi@gmail.com
    password: Mama9848

    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

          starttls:
            enable: true


logging:
  level:
    org:
      hibernate:
        type: trace

security:
  oauth2:
    resource:
      filter-order: 3
      #token-info-url: http://localhost:9090/oauth/check_token

amazonProperties:
  endpointUrl: http://oxobucket.s3-us-west-1.amazonaws.com
  accessKey: AKIAWIVXFQZTHJXOOH6S
  secretKey: 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
  bucketName: oxobucket

check-user-scopes: true