server:
  port: 9090
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/OAuthDB?createDatabaseIfNotExist=true
    url: jdbc:mysql://mysql-auth-server:3306/OAuthDB?createDatabaseIfNotExist=true
    username: root
    password: sudi
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

security:
  oauth2:
    resource:
      filter-order: 3
      #token-info-url: http://localhost:9090/oauth/check_token

check-user-scopes: true