package com.oauth2.general.dto;

import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.Digits;
import javax.validation.constraints.Email;
import javax.validation.constraints.NotNull;

public class UserCreateDTO {

    @NotNull
    @Email
    @ApiModelProperty(notes = "email used by the user of the app",required = true)
    private String email;

    @NotNull
    @ApiModelProperty(notes = "Password of the user",required = true)
    private String password;

    @NotNull
    @ApiModelProperty(notes = "Password confirmation field, Should match with password",required = true)
    private String password_confirm;

    @ApiModelProperty(notes = "Autogenerated password used to uniquely identifying the user")
    private String userID;

    @ApiModelProperty(notes = "role/roles assigned to this user")
    private String[] roles;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String[] getRoles() {
        return roles;
    }

    public void setRoles(String[] roles) {
        this.roles = roles;
    }

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public String getPassword_confirm() {
        return password_confirm;
    }

    public void setPassword_confirm(String password_confirm) {
        this.password_confirm = password_confirm;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "UserCreateDTO{" +
                "email='" + email + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
